import RJS from '../core/RJS';
import { Sprite } from 'phaser-ce';
import RJSSprite from '../components/RJSSprite';
export declare function initSplash(game: RJS): Sprite;
export declare function initLoadingBar(game: RJS): RJSSprite;
export declare function preparePath(path: string, game: RJS): string;
export declare function preloadBackground(bgName: string, game: RJS): void;
export declare function preloadCGS(cgName: string, game: RJS): void;
export declare function preloadAudio(audioName: string, audioType: any, game: RJS): void;
export declare function preloadCharacter(chName: string, game: RJS): void;
export declare function preloadExtra(asset: string, type: string, game: RJS): void;
export declare function loadStyle(href: any, callback?: any): void;
