import RJS from '../core/RJS';
import { Text } from 'phaser-ce';
export declare function preparePath(path: string, game: RJS): string;
export declare function preloadBackground(bgName: string, game: RJS): void;
export declare function preloadCGS(cgName: string, game: RJS): void;
export declare function preloadAudio(audioName: string, audioType: any, game: RJS): void;
export declare function preloadCharacter(chName: string, game: RJS): void;
export declare function preloadExtra(asset: string, type: string, game: RJS): void;
export declare function setTextStyles(text: string, text_obj: Text): string;
export declare function toHexColor(color: any): number;
export declare function loadStyle(href: any, callback?: any): void;
